# Numpy

In [2]:
import numpy as np
x = [1,2,3,4,5]
nums = np.array([[1,2,3],[6,7,8],[9,10,11]])
type(nums)

numpy.ndarray

In [3]:
nums

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
# arange
nums = np.arange(2,7)

In [5]:
nums 

array([2, 3, 4, 5, 6])

In [6]:
# arange with step
num = np.arange(2,7,2)

In [7]:
num

array([2, 4, 6])

In [8]:
#Zeros 
zeros = np.zeros(4)

In [9]:
zeros

array([0., 0., 0., 0.])

In [10]:
type(zeros[0])

numpy.float64

In [11]:
#2-D Zeros
zeros = np.zeros((4,3),int)

In [12]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
#one
ones = np.ones(4)

In [14]:
ones

array([1., 1., 1., 1.])

In [15]:
ones = np.ones((4,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#linspace
lin = np.linspace(1,10,10)

In [18]:
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
lin = np.linspace(1,10,20)

In [20]:
lin

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
# eye - identical matrix
idn = np.eye(4)
idn

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# Random - rand (under numpy)
random = (5*np.random.rand(2,3))
random

array([[1.7410221 , 0.29655863, 1.90634769],
       [2.18291095, 4.20473668, 3.72170877]])

In [23]:
randomNum = np.random.randint(10,100,10)
randomNum

array([46, 62, 86, 89, 19, 73, 27, 93, 74, 75])

In [24]:
# reshape
nums = np.arange(1,17)

In [25]:
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
num1 = nums.reshape(4,4)
num1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
# min and max values
min = np.min(num1)
min

1

In [28]:
max = np.max(num1)

In [29]:
max

16

In [30]:
max = np.max(nums)

In [31]:
max

16

In [32]:
random.argmax() #the index of maximum element in the random array is answer

4

In [33]:
random.argmin()

1

In [34]:
nums[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [35]:
nums[0:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
num2 = np.array(([1,2,3,6],[4,5,6,7],[7,8,9,8],[10,11,12,9]))

In [37]:
num2[1,2]

6

In [38]:
num2[:,1]

array([ 2,  5,  8, 11])

In [39]:
num1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
num3 = num1+num2

In [41]:
num3

array([[ 2,  4,  6, 10],
       [ 9, 11, 13, 15],
       [16, 18, 20, 20],
       [23, 25, 27, 25]])

In [42]:
num4 = num1+10

In [43]:
num4

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [44]:
num5 = np.log(num2)

In [45]:
num5

array([[0.        , 0.69314718, 1.09861229, 1.79175947],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [1.94591015, 2.07944154, 2.19722458, 2.07944154],
       [2.30258509, 2.39789527, 2.48490665, 2.19722458]])

In [46]:
num5 = np.sqrt(num2)
num5

array([[1.        , 1.41421356, 1.73205081, 2.44948974],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.64575131, 2.82842712, 3.        , 2.82842712],
       [3.16227766, 3.31662479, 3.46410162, 3.        ]])

In [47]:
num6 = np.sin(num4)

In [48]:
num6

array([[-0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725],
       [ 0.14987721,  0.91294525,  0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836, -0.13235175,  0.76255845]])

In [49]:
x = np.array([2,4])
y = np.array([1,3])

In [50]:
dot_prod = 0;
for a,b in zip(x,y):
    dot_prod+=a*b
    print(dot_prod)

2
14


In [51]:
l1 = [1,2,3]
l2 = [4,5,6]
a_zip    =  zip(l1,l2)
a_zip

In [52]:
z_list = list(a_zip)
z_list

[(1, 4), (2, 5), (3, 6)]

In [53]:
a = x*y
a

array([ 2, 12])

In [54]:
a.sum()

14

In [55]:
x = np.array(([1,2,3],[4,5,6],[7,8,9]))
y = np.array(([1,2,4],[5,6,7],[3,8,1]))
z = np.dot(x,y)

In [56]:
z

array([[ 20,  38,  21],
       [ 47,  86,  57],
       [ 74, 134,  93]])

In [57]:
x.shape

(3, 3)

# Pandas

Pandas we have 2 data structures
1. Series = immutable - 1D 
2. DataFrame

In [58]:
import pandas as pd

In [59]:
series1 = pd.Series([1,2.5,3,4])
series1

0    1.0
1    2.5
2    3.0
3    4.0
dtype: float64

In [60]:
import numpy as np
import sys
sys.__stdout__ = sys.stdout #nothing use here happened
fruits = np.array(['Apple', 'Orange', 'Mango','Pear'])
series2 = pd.Series(fruits)

In [61]:
fruits

array(['Apple', 'Orange', 'Mango', 'Pear'], dtype='<U6')

In [62]:
series2

0     Apple
1    Orange
2     Mango
3      Pear
dtype: object

In [63]:
# DataFrame
df = pd.DataFrame({"Col1": [1,2,3,4,5], "Col2": ['A','Column','with','A','String'], "col3": [1.2,2.3,3.4,4.5,5.6], "col4": [True, False, True, False, True]})

In [64]:
df

Col1    Col2  col3   col4
0     1       A   1.2   True
1     2  Column   2.3  False
2     3    with   3.4   True
3     4       A   4.5  False
4     5  String   5.6   True

In [65]:
a = 'bhavesh'
type(a)

str

In [66]:
# Describe
df.describe()

Col1      col3
count  5.000000  5.000000
mean   3.000000  3.400000
std    1.581139  1.739253
min    1.000000  1.200000
25%    2.000000  2.300000
50%    3.000000  3.400000
75%    4.000000  4.500000
max    5.000000  5.600000

In [67]:
#importing or reading of the data
# CSV - Comma Seperated Value
data = pd.read_csv('adult.csv')

In [68]:
data

age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7   
1       38       Private   89814       HS-grad                9   
2       28     Local-gov  336951    Assoc-acdm               12   
3       44       Private  160323  Some-college               10   
4       18             ?  103497  Some-college               10   
...    ...           ...     ...           ...              ...   
48837   27       Private  257302    Assoc-acdm               12   
48838   40       Private  154374       HS-grad                9   
48839   58       Private  151910       HS-grad                9   
48840   22       Private  201490       HS-grad                9   
48841   52  Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 15 columns]